"""added unique check in UserItems for user_id and item_id

Revision ID: 096da9f608f8
Revises: e26ee1fdf2e3
Create Date: 2026-09-22 13:24:16.874694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096da9f608f8'
down_revision: Union[str, Sequence[str], None] = 'e26ee1fdf2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_items', 'item_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_unique_constraint('uq_user_item', 'user_items', ['user_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_item', 'user_items', type_='unique')
    op.alter_column('user_items', 'item_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('user_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
