"""change description

Revision ID: 0fa7979e7321
Revises: 2672a6027015
Create Date: 2026-06-02 15:35:50.427196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa7979e7321'
down_revision: Union[str, Sequence[str], None] = '2672a6027015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_effects', 'timeout',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_effects', 'timeout',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
