"""unique bet theme per server

Revision ID: 8455a67c7710
Revises: 89c5355dde78
Create Date: 2026-09-21 14:05:45.805404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8455a67c7710'
down_revision: Union[str, Sequence[str], None] = '89c5355dde78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bets_server_theme', 'bets', ['server_id', 'theme'])
    # ### end Alembic commands ###

def downgrade():
    op.drop_constraint("uq_bets_server_theme", "bets", type_="unique")