"""item_changes

Revision ID: 89c5355dde78
Revises: f0ab65419a0c
Create Date: 2026-07-01 22:55:10.147595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c5355dde78'
down_revision: Union[str, Sequence[str], None] = 'f0ab65419a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_prompts')
    op.add_column('item_types', sa.Column('item_name', sa.Text(), nullable=True))
    op.add_column('item_types', sa.Column('in_casino', sa.Boolean(), nullable=True))
    op.add_column('item_types', sa.Column('on_author', sa.Boolean(), nullable=True))
    op.add_column('item_types', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('item_types', 'item_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_types', sa.Column('item_type', postgresql.ENUM('frog', 'gentlemen', 'fake_admin', 'snowball', name='itemtype'), autoincrement=False, nullable=True))
    op.drop_column('item_types', 'duration')
    op.drop_column('item_types', 'on_author')
    op.drop_column('item_types', 'in_casino')
    op.drop_column('item_types', 'item_name')
    op.create_table('ai_prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('system', 'assistant', 'user', name='airoletype'), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_prompts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_prompts_pkey'))
    )
    # ### end Alembic commands ###
